### ISSUE TITLE
healpix URL hosting

### ISSUE THREAD

**Issue by jracusin** [nasa-gcn/gcn-avro-schema#14]
We need a way for healpix maps to be hosted on GCN somewhere, and include links in schema.  Or the links could be to outside servers, but would be cleaner to be hosted by us.

**Comment by lpsinger** [comment]
I think we were just going to have the HEALPix maps inline.

**Comment by jracusin** [comment]
Do you mean sending the healpix files via kafka as part of the schema?

**Comment by lpsinger** [comment]
Yes.

**Comment by jracusin** [comment]
Ok, issue remains that we need to figure out how to do this in the schema.

**Comment by eburnsastro** [comment]
The delay to hosting at HEASARC is problematic. I think we need to house them within GCN. Scott already hosts some files for a few groups.

**Comment by jracusin** [comment]
Solution is to host inline, but need to figure out how.
